# @see https://github.com/codeclimate/codeclimate-rubocop/issues/187
# require: rubocop-performance

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Layout/CaseIndentation:
  EnforcedStyle: end

Style/CollectionMethods:
  PreferredMethods:
    reduce: inject
    inject: inject

Style/Lambda:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/MethodLength:
  Max: 24

Metrics/BlockLength:
  IgnoredMethods: [it, describe, context, feature, freeze, specify, define, renum]

Layout/LineLength:
  Max: 120

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  IgnoredMethods: [let, let!, subject, lambda, proc, it, expect]

Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false
