---
language: ruby
sudo: false
cache: bundler
rvm:
  - 3.0.0
  - 2.7.2
  - 2.6.6
before_install: gem install bundler -v 2.0.2
script: 'bundle exec rspec spec'
branches:
  only:
    - master
notifications:
  email: false
