---
language: ruby
sudo: false
cache: bundler
rvm:
  - 2.7.1
  - 2.6.5
  - 2.7.0
before_install: gem install bundler -v 2.0.2
script: 'bundle exec rspec spec'
branches:
  only:
    - master
notifications:
  email: false
